env:
 global:
  - CABALVER=1.20
 matrix:
  - GHCVER=7.0.4
  - GHCVER=7.2.2
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.3
  - GHCVER=head

matrix:
 allow_failures:
  - env: GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq
 - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER
 - export PATH="/opt/ghc/$GHCVER/bin:$PATH"

install:
 - cabal-$CABALVER update
 - ghc --version
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGLRaw.git
 - cd OpenGLRaw
 - cabal-$CABALVER install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/GLURaw.git
 - cd GLURaw
 - cabal-$CABALVER install --enable-documentation
 - popd
 - ghc-pkg list

script:
 - cabal-$CABALVER install --enable-documentation
 - cabal-$CABALVER sdist
 - ghc-pkg list
