# It seems that we can't use the CABALVER and GHCVER environment variables in a
# toplevel addons.apt.packages section, so we have to duplicate things below.
matrix:
  include:
   - env: CABALVER=1.16 GHCVER=7.0.4
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.16
          - ghc-7.0.4
   - env: CABALVER=1.16 GHCVER=7.2.2
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.16
          - ghc-7.2.2
   - env: CABALVER=1.16 GHCVER=7.4.2
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.16
          - ghc-7.4.2
   - env: CABALVER=1.16 GHCVER=7.6.3
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.16
          - ghc-7.6.3
   - env: CABALVER=1.20 GHCVER=7.8.4
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.20
          - ghc-7.8.4
   - env: CABALVER=1.22 GHCVER=7.10.2
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-1.22
          - ghc-7.10.2
   - env: CABALVER=head GHCVER=head
     addons:
       apt:
         sources:
          - hvr-ghc
         packages:
          - cabal-install-head
          - ghc-head
  allow_failures:
   - env: CABALVER=head GHCVER=head

sudo: false

# The packages from the PPA don't put this into the PATH automatically.
install:
 - export PATH="/opt/cabal/$CABALVER/bin:/opt/ghc/$GHCVER/bin:$PATH"

before_script:
 - cabal --version
 - cabal update
 - ghc --version
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGLRaw.git
 - cd OpenGLRaw
 - cabal install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/GLURaw.git
 - cd GLURaw
 - cabal install --enable-documentation
 - popd
 - ghc-pkg list

script:
 - cabal install --enable-documentation
 - cabal sdist

after_script:
 - ghc-pkg list
