language: haskell
before_install:
  - ghc-pkg list
  - pushd ..
  - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGLRaw.git
  - cd OpenGLRaw
  - git checkout
  - cabal install
  - popd
  - ghc-pkg list
script:
  - cabal install --enable-documentation
